apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-spring-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-spring-java
  template:
    metadata:
      labels:
        app: jenkins-spring-java
    spec:
      containers:
        - name: jenkins-spring-java
          image: ratnparkhiv/jenkins-spring-java:1.0.0-7
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
