apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-spring-java
  labels:
    app: jenkins-spring-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-spring-java
  template:
    metadata:
      labels:
        app: jenkins-spring-java
    spec:
      containers:
      - name: jenkins-spring-java
        image: jenkins-spring-java:replaceImageTag
        ports:
        - containerPort: 8080
